<a href="https://colab.research.google.com/github/Bloorel/-/blob/main/%D0%9B%D0%B0%D0%B1_1%D0%9F%D0%B0%D1%80%D1%85%D0%BE%D0%BC%D0%B5%D0%BD%D0%BA%D0%BE_%D0%86%D0%B2%D0%B0%D0%BD_%D0%94%D0%BC%D0%B8%D1%82%D1%80%D0%BE%D0%B2%D0%B8%D1%87_%D0%B2%D0%B0%D1%80%D1%96%D0%B0%D0%BD%D1%82_14.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [7]:
#Варіант 14
# Завдання 1: Створити одновимірний масив (вектор) із геометричною прогресією,
# де кожне наступне число менше попереднього в 3 рази, починаючи з 81, та вивести його значення.

import numpy as np

# Початкове значення
start = 81
# Кількість елементів
n = 6
# Знаменник геометричної прогресії
r = 1/3

# Створюємо масив
vector = np.array([start * (r**i) for i in range(n)])

# Вивід результату
print(vector)





# Завдання 2: Створити двовимірний масив (матрицю) 3x3,
# заповнити його оберненими значеннями дробових частин від ділення кожного числа на 2,
# починаючи з 1, та вивести його значення.

import numpy as np

# Розмір матриці
rows, cols = 3, 3

# Функція для обчислення оберненого значення дробової частини
def inverse_fraction(n):
    fraction = (n / 2) % 1  # Отримуємо дробову частину
    return 1 / fraction if fraction != 0 else 0  # Обернене значення дробової частини

# Створюємо матрицю
matrix = np.array([[inverse_fraction(i + j * cols + 1) for i in range(cols)] for j in range(rows)])

# Вивід результату
print(matrix)




# Завдання 3: Створити масив 4x4, заповнити його випадковими натуральними числами від 1 до 10
# і знайти мінімальний елемент.

import numpy as np

# Розмір матриці
rows, cols = 4, 4

# Генеруємо матрицю з випадковими числами від 1 до 10
matrix = np.random.randint(1, 11, size=(rows, cols))

# Знаходимо мінімальний елемент
min_element = np.min(matrix)

# Вивід результату
print("Матриця:\n", matrix)
print("Мінімальний елемент:", min_element)





# Завдання 4: Створити масив 5x5, заповнити його випадковими дійсними числами в діапазоні [0, 1],
# та знайти середнє арифметичне елементів, розташованих на побічній діагоналі.

import numpy as np

# Розмір матриці
size = 5

# Генеруємо матрицю з випадковими числами від 0 до 1
matrix = np.random.rand(size, size)

# Отримуємо елементи побічної діагоналі (з правого верхнього кута в лівий нижній)
secondary_diag = [matrix[i, size - 1 - i] for i in range(size)]

# Обчислюємо середнє арифметичне
mean_value = np.mean(secondary_diag)

# Вивід результату
print("Матриця:\n", matrix)
print("Елементи побічної діагоналі:", secondary_diag)
print("Середнє арифметичне:", mean_value)





# Завдання 5: Створити два одновимірні масиви розміром 5,
# заповнити їх випадковими цілими числами в діапазоні від 1 до 20
# та виконати на них поелементні операції додавання, віднімання та множення.

import numpy as np

# Розмір масивів
size = 5

# Генеруємо два масиви з випадковими числами від 1 до 20
array1 = np.random.randint(1, 21, size)
array2 = np.random.randint(1, 21, size)

# Виконуємо поелементні операції
sum_result = array1 + array2
diff_result = array1 - array2
prod_result = array1 * array2

# Вивід результату
print("Масив 1:", array1)
print("Масив 2:", array2)
print("Додавання:", sum_result)
print("Віднімання:", diff_result)
print("Множення:", prod_result)




# Завдання 6: Створити дві матриці 3x3, заповнити їх довільними цілими числами від 5 до 10
# та знайти їх добуток.

import numpy as np

# Розмір матриць
size = 3

# Генеруємо дві матриці з випадковими цілими числами від 5 до 10
matrix1 = np.random.randint(5, 11, (size, size))
matrix2 = np.random.randint(5, 11, (size, size))

# Обчислюємо добуток матриць
matrix_product = np.dot(matrix1, matrix2)

# Вивід результату
print("Матриця 1:\n", matrix1)
print("Матриця 2:\n", matrix2)
print("Добуток матриць:\n", matrix_product)




# Завдання 7: Створити дві матриці розміром 2x3 та 3x4,
# заповнити їх випадковими цілими числами від 1 до 5 та перемножити їх.

import numpy as np

# Генеруємо першу матрицю 2x3
matrix1 = np.random.randint(1, 6, (2, 3))

# Генеруємо другу матрицю 3x4
matrix2 = np.random.randint(1, 6, (3, 4))

# Виконуємо множення матриць
matrix_product = np.dot(matrix1, matrix2)

# Вивід результату
print("Матриця 1 (2x3):\n", matrix1)
print("Матриця 2 (3x4):\n", matrix2)
print("Добуток матриць (2x4):\n", matrix_product)




# Завдання 8: Створити матрицю 3x3, заповнити її випадковими цілими числами від 1 до 10
# та знайти її обернену матрицю.

import numpy as np

# Генеруємо матрицю 3x3 з випадковими цілими числами від 1 до 10
matrix = np.random.randint(1, 11, (3, 3))

# Перевіряємо, чи матриця має обернену (визначник не дорівнює 0)
determinant = np.linalg.det(matrix)

if determinant != 0:
    inverse_matrix = np.linalg.inv(matrix)  # Обернена матриця
    print("Матриця:\n", matrix)
    print("Обернена матриця:\n", inverse_matrix)
else:
    print("Матриця:\n", matrix)
    print("Обернена матриця не існує, оскільки її визначник дорівнює 0.")
# Завдання 9: Створити матрицю 4x4, заповнити її випадковими дійсними числами від 0 до 1
# та транспонувати її.

import numpy as np

# Генеруємо матрицю 4x4 з випадковими дійсними числами від 0 до 1
matrix = np.random.rand(4, 4)

# Транспонуємо матрицю
transposed_matrix = matrix.T

# Вивід результату
print("Матриця:\n", matrix)
print("Транспонована матриця:\n", transposed_matrix)



# Завдання 10: Створити матрицю розміром 3x4 та вектор розміром 4x1,
# заповнити матрицю випадковими дійсними числами від 0 до 1,
# а вектор - випадковими дійсними числами від 0 до 1, і знайти їх добуток.

import numpy as np

# Генеруємо матрицю 3x4 з випадковими дійсними числами від 0 до 1
matrix = np.random.rand(3, 4)

# Генеруємо вектор 4x1 з випадковими дійсними числами від 0 до 1
vector = np.random.rand(4, 1)

# Обчислюємо добуток матриці на вектор
product = np.dot(matrix, vector)

# Вивід результату
print("Матриця (3x4):\n", matrix)
print("Вектор (4x1):\n", vector)
print("Добуток матриці на вектор:\n", product)






# Завдання 12: Створити дві матриці розміром 7x7, заповнити їх випадковими цілими числами в діапазоні від 1 до 10
# та знайти їхню різницю.

import numpy as np

# Генеруємо дві матриці 7x7 з випадковими цілими числами від 1 до 10
matrix1 = np.random.randint(1, 11, (7, 7))
matrix2 = np.random.randint(1, 11, (7, 7))

# Обчислюємо різницю між матрицями
difference = matrix1 - matrix2

# Вивід результату
print("Матриця 1 (7x7):\n", matrix1)
print("Матриця 2 (7x7):\n", matrix2)
print("Різниця між матрицями:\n", difference)






# Завдання 13: Створити дві матриці розміром 2x2, заповнити їх випадковими цілими числами в діапазоні від -5 до 5
# та знайти суму їх елементів.

import numpy as np

# Генеруємо дві матриці 2x2 з випадковими цілими числами від -5 до 5
matrix1 = np.random.randint(-5, 6, (2, 2))
matrix2 = np.random.randint(-5, 6, (2, 2))

# Обчислюємо суму елементів матриць
sum_matrix1 = np.sum(matrix1)
sum_matrix2 = np.sum(matrix2)

# Вивід результату
print("Матриця 1 (2x2):\n", matrix1)
print("Сума елементів матриці 1:", sum_matrix1)

print("Матриця 2 (2x2):\n", matrix2)
print("Сума елементів матриці 2:", sum_matrix2)






# Завдання 14: Створити матрицю розміром 3x3, заповнити її випадковими цілими числами в діапазоні від 1 до 10
# та знайти добуток елементів матриці, які менше за їх середнє арифметичне значення.

import numpy as np

# Генеруємо матрицю 3x3 з випадковими цілими числами від 1 до 10
matrix = np.random.randint(1, 11, (3, 3))

# Обчислюємо середнє арифметичне всіх елементів матриці
mean_value = np.mean(matrix)

# Фільтруємо елементи, які менші за середнє арифметичне
filtered_elements = matrix[matrix < mean_value]

# Обчислюємо добуток елементів, які менші за середнє арифметичне
product = np.prod(filtered_elements)

# Вивід результату
print("Матриця (3x3):\n", matrix)
print("Середнє арифметичне елементів матриці:", mean_value)
print("Елементи матриці, менші за середнє арифметичне:", filtered_elements)
print("Добуток елементів, менших за середнє арифметичне:", product)









# Завдання 15: Створити матрицю розміром 3x3, заповнити її випадковими дійсними числами в діапазоні від -1 до 1
# та знайти вектор-стовпчик, що містить найбільше ціле значення в кожному рядку матриці.

import numpy as np

# Генеруємо матрицю 3x3 з випадковими дійсними числами від -1 до 1
matrix = np.random.uniform(-1, 1, (3, 3))

# Для кожного рядка знаходимо найбільше ціле значення
max_int_values = np.floor(matrix).astype(int).max(axis=1)

# Формуємо вектор-стовпчик
column_vector = max_int_values.reshape(-1, 1)

# Вивід результату
print("Матриця (3x3):\n", matrix)
print("Вектор-стовпчик, що містить найбільше ціле значення в кожному рядку матриці:\n", column_vector)


[81.         27.          9.          3.          1.          0.33333333]
[[2. 0. 2.]
 [0. 2. 0.]
 [2. 0. 2.]]
Матриця:
 [[10  3 10  8]
 [ 9  5 10  9]
 [ 1  3  6  2]
 [ 5  6  3  5]]
Мінімальний елемент: 1
Матриця:
 [[0.26947133 0.19271221 0.27443076 0.96039011 0.80108199]
 [0.78894312 0.79959113 0.03966088 0.39142002 0.79974991]
 [0.85704828 0.63617361 0.67326298 0.60660369 0.43760406]
 [0.43727353 0.37845617 0.30119177 0.84399318 0.10450213]
 [0.41854607 0.21332848 0.55059993 0.14295403 0.24309666]]
Елементи побічної діагоналі: [np.float64(0.8010819940458477), np.float64(0.3914200174989909), np.float64(0.6732629843891762), np.float64(0.37845616559419726), np.float64(0.4185460687712562)]
Середнє арифметичне: 0.5325534460598937
Масив 1: [ 1 14  4  6  9]
Масив 2: [ 5  4 14 16 20]
Додавання: [ 6 18 18 22 29]
Віднімання: [ -4  10 -10 -10 -11]
Множення: [  5  56  56  96 180]
Матриця 1:
 [[ 8  7  8]
 [ 7 10  7]
 [ 6  9  5]]
Матриця 2:
 [[ 9 10  7]
 [ 6  5 10]
 [10  6  6]]
Добуток матриць:
 [